services:
  react:
    image: sberston/todo-react:latest
    ports:
    - "8080:8080"
  controller:
    image:  sberston/todo-app-backend
    ports: 
    - "3000:3000"
    depends_on:
    - "database"
  database:
    image: sberston/todo-psql:latest
    ports:
    - "5432:5432"
