apiVersion: v1
kind: Service
metadata:
  name: todo-app-headless
spec:
  clusterIP: None
  selector:
    app: todo-app-ssl
  ports:
  - name: https
    port: 8443
    targetPort: 8443
    protocol: TCP