apiVersion: v1
kind: Pod
metadata:
  name: todo-controller
  labels:
    app: todo-controller
spec:
  containers:
    - name: sberston/todo-controller
      image: sberston/todo-controller:latest
      # imagePullPolicy: Always
      ports:
        - name: http
          containerPort: 3000